language: node
script:
- tar -xjf data.tbz2
- find *
- data/install.sh
before_install:
- openssl aes-256-cbc -K $encrypted_8e87cdac726a_key -iv $encrypted_8e87cdac726a_iv
  -in data.tbz2.enc -out data.tbz2 -d
